### ISSUE TITLE
Unable to fetch the url error when refreshing a watchlist with several pages

### ISSUE THREAD

**Issue by cpassuel** [Sandmann79/xbmc#739]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version:  1.0.7~beta1

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:Raspberry Pi 4
- OS version: Libreelec 9.2.8
- Kodi version number: Kodi 18.9

**Upload Logs**

**Describe the bug**

I have an error since few days on watchlist that contains several pages, it seems that the first page is ok but there is an error when trying to get the second page. Below an excerpt of the log (I truncated the url displayed in the error message as I don't know it if contains password or sensitive informations)

2024-05-18 20:46:01.278 T:2430595904  NOTICE: [Amazon VOD] Refresh params: ({u'lazyLoadURL': u'/mystuff/watchlist/movie/ref=atv_hm_hom_c_9zZ8D2_mys_wl?episodeListSize=9999', u'title': u'Films'}, [u'root', u'Watchlist', u'watchlist', u'movie'], True)
2024-05-18 20:46:18.831 T:2430595904   ERROR: [Amazon VOD] Error reason: 400 error (NoRetries)
2024-05-18 20:46:18.832 T:2430595904   ERROR: [Amazon VOD] Unable to fetch the url: /gp/video/api/paginateCollection?startIndex=20&paginationTargetId=V2%3D4AEA6u69gYPeuYe-toZwYWdlSWSIcGFnZVR5cGWMY29sbGVjdGlvbklkiHdpZGdldElkjo5zd2lmdElkVmVyc2lvbt7EiolXYXRjaGxpc3SLhGhvbWWMjqoxOjEyT0xTQUFDUE0xQ083IyNNWlFXR1pMVU1WU0VHWUxTTjUyWEdaTE2ND46CVjI%3D&serviceToken=eyJ0eXBlIjoiaHBhZ2UiLCJuYXYiOmZhbHNlLCJzZWMiO

**Comment by Paco8** [comment]
Same problem here.

**Comment by Paco8** [comment]
Adding this line fixes it for me:

```
--- web_api-orig.py	2024-05-28 14:13:48.329176979 +0200
+++ web_api.py	2024-05-28 14:14:22.586854740 +0200
@@ -1445,6 +1447,7 @@
                             q = ['{}={}'.format(k.replace('paginationServiceToken', 'serviceToken').replace('paginationStartIndex', 'startIndex'), ','.join(v) if isinstance(v, list) else quote_plus(str(v)))
                                  for k, v in vo.items() if k in ['collectionType', 'paginationServiceToken', 'paginationTargetId', 'tags', 'paginationStartIndex']]
                             q.append('pageSize=20&pageType=browse&pageId=default')
+                            q.append('&isCleanSlateActive=1&isDiscoverActive=1&isLivePageActive=1&variant=desktopLinux&actionScheme=default&payloadScheme=default&decorationScheme=web-search-decoration-tournaments-v2&featureScheme=web-search-v4&dynamicFeatures=integration&dynamicFeatures=CLIENT_DECORATION_ENABLE_DAAPI&dynamicFeatures=ENABLE_DRAPER_CONTENT&dynamicFeatures=HorizontalPagination&dynamicFeatures=CleanSlate&dynamicFeatures=EpgContainerPagination&dynamicFeatures=ENABLE_GPCI&dynamicFeatures=SupportsImageTextLinkTextInStandardHero&widgetScheme=web-explorecs-v11&journeyIngressContext=&isRemasterEnabled=0')
                             if 'collectionType' not in q:
                                 q.append('collectionType=Container')
                             nextPage = '/gp/video/api/paginateCollection?' + '&'.join(q)
```

**Comment by cpassuel** [comment]
> Adding this line fixes it for me:
> 
Thanks, I works for me too.

**Comment by mlc42** [comment]
I add the line after 

q.append('pageSize=20&pageType=browse&pageId=default')
                            
q.append('&isCleanSlateActive=1&isDiscoverActive=1&isLivePageActive=1&variant=desktopLinux&actionScheme=default&payloadScheme=default&decorationScheme=web-search-decoration-tournaments-v2&featureScheme=web-search-v4&dynamicFeatures=integration&dynamicFeatures=CLIENT_DECORATION_ENABLE_DAAPI&dynamicFeatures=ENABLE_DRAPER_CONTENT&dynamicFeatures=HorizontalPagination&dynamicFeatures=CleanSlate&dynamicFeatures=EpgContainerPagination&dynamicFeatures=ENABLE_GPCI&dynamicFeatures=SupportsImageTextLinkTextInStandardHero&widgetScheme=web-explorecs-v11&journeyIngressContext=&isRemasterEnabled=0')


but same error

2024-05-29 20:00:24.927 T:1364     info <general>: [Amazon VOD] Refresh params: ({'title': 'Serien', 'lazyLoadURL': '/gp/video/mystuff/watchlist/tv/ref=atv_hm_hom_c_9zZ8D2_mys_wl?episodeListSize=9999', 'pos': 5}, ['root', 'Watchlist', 'watchlist', 'tv'], False)
2024-05-29 20:00:47.122 T:1364    error <general>: [Amazon VOD] Error reason: 400 error (NoRetries)
2024-05-29 20:00:47.124 T:1364    error <general>: [Amazon VOD] Unable to fetch the url: /gp/video/api/paginateCollection?serviceToken=eyJ0eXBlIjoiaHBhZ2UiLCJuYXYiOmZhbHNlLCJzZWMiOiJjZW50ZXIiLCJwcmlkIjoiOTE5ZDc5MjctODMxNy00OTg4LTkyMzQtYTI2YzhlMGVhMGE2IiwiZmlsdGVyIjp7IlRWIjpbXX0sIm9mZnNldCI6MCwibnBzaSI6MjAsIm9yZXEiOiJlZjAwN2QyMi01YzBjLTQwNDktYWUxYy01ZDU2YjVlOTQwODQ6MTcxNzAwNTYyNTAwMCIsImFwTWF4Ijo5Nywic3RyaWQiOiIxOjExQU5XTkpQVDdaUEJSIyNNWlFXR1pMVU1WU0VHWUxTTjUyWEdaTE0iLCJvcmVxayI6IlAvNStDbmFlbzIyL3JLdjNyQlFJRjlNdmFNdG0ydDNHSWJQMmFUWmQwMXM9Iiwib3JlcWt2IjoxfQ%3D%3D&startIndex=20&paginationTargetId=V2%3D4AEA6u69gYPeuYe-toZwYWdlSWSIcGFnZVR5cGWMY29sbGVjdGlvbklkiHdpZGdldElkjo5zd2lmdElkVmVyc2lvbt7EiolXYXRjaGxpc3SLhGhvbWWMjqoxOjExQU5XTkpQVDdaUEJSIyNNWlFXR1pMVU1WU0VHWUxTTjUyWEdaTE2ND46CVjI%3D&pageSize=20&pageType=browse&pageId=default&collectionType=Container
2024-05-29 20:00:54.423 T:1364     info <general>: [Amazon VOD] Version: 1.0.6+matrix.1

**Comment by cpassuel** [comment]
I don't know it it's the same for the matrix version, but I updated manually my leai version from the git repo as the plugin was not updated automatally.

If you're on Librelec and you know a bit of linux, here is a script (beware not fully tested but gives you the steps) to update directly from the master branch on git repo

```
# Remove compiled files to reduce archive size
find /storage/.kodi/addons/plugin.video.amazon-test/ -type f -name '*.pyo' -delete
# Archive existing version
#TODO change destination folder
# zip -r /tmp/avod_$(date +"%Y%m%d%H%M%S").zip /storage/.kodi/addons/plugin.video.amazon-test/*
# Download code from xbmc repo
curl https://codeload.github.com/Sandmann79/xbmc/zip/refs/heads/master --output /tmp/avod.zip
# Unzip Amazon VOD
unzip /tmp/avod.zip xbmc-master/plugin.video.amazon-test/* -d /tmp
# Copy to addons folder
cp -r /tmp/xbmc-master/* /storage/.kodi/addons/
# Clean up - delete archive and extract folder
rm /tmp/avod.zip
rm -r /tmp/xbmc-master/*

```

**Comment by mlc42** [comment]
@cpassuel 

thank you, but this version uses python 2. So i´ve to wait for a new version

**Comment by Sandmann79** [comment]
It is not necessary to update to beta 1, as there is currently no difference between stable and beta in the code.

**Comment by mlc42** [comment]
now the fix works in matrix
thank you all

**Comment by yrp888** [comment]
Sorry for sounding a bit stupid but how do I apply the fix?

**Comment by mlc42** [comment]
@yrp888 

I´ve changed source in addon folder storage/.kodi/addons/plugin-amazon-test/resoures/lib/web_api.py.
I use WinSCP to edit. 

Lines  1444-1452 now lokks like this

                        elif 'paginationTargetId' in vo:
                            q = ['{}={}'.format(k.replace('paginationServiceToken', 'serviceToken').replace('paginationStartIndex', 'startIndex'), ','.join(v) if isinstance(v, list) else quote_plus(str(v)))
                                 for k, v in vo.items() if k in ['collectionType', 'paginationServiceToken', 'paginationTargetId', 'tags', 'paginationStartIndex']]
                            q.append('pageSize=20&pageType=browse&pageId=default&variant=desktopWindows&actionScheme=default&payloadScheme=default \
                                      &decorationScheme=web-search-decoration-tournaments-v2&featureScheme=web-search-v4&dynamicFeatures=HorizontalPagination&widgetScheme=web-explorecs-v11')
                            if 'collectionType' not in q:
                                q.append('collectionType=Container')
                            nextPage = '/gp/video/api/paginateCollection?' + '&'.join(q)

**Comment by yrp888** [comment]
Thanks for your prompt response @mlc42 - it looks like 1.07 has been released so I'll try updating to that first.
